/// <reference path="C:\Projects\typescript-node-definitions\node.d.ts" />
/// <reference path="C:\Projects\typescript-node-definitions\request.d.ts" />
/// <reference path="C:\Projects\typescript-node-definitions\nconf.d.ts" />
/// <reference path="C:\Projects\typescript-node-definitions\gently.d.ts" />
/// <reference path="C:\Projects\typescript-node-definitions\aws-sdk.d.ts" />
/// <reference path="C:\Projects\textteaser.js\TextTeaser\lib\index.ts" />
///<reference path="C:\Projects\typescript-node-definitions\nodeunit.d.ts"/>
///<reference path="C:\Projects\typescript-node-definitions\nock.d.ts"/>
///<reference path="C:\Projects\typescript-node-definitions\async.d.ts"/>